import { Metadata } from "next";
import PostComponent from "@/components/post";
import { getPostSlug } from "@/app/(pages)/post.api";

export async function generateMetadata({
  params,
}: {
  params: { slug: string };
}): Promise<Metadata> {
  const res = await getPostSlug({ slug: params.slug });

  if (res && res.success) {
    return {
      title: `${res.data.title} - c0deviews`,
      description: res.data.body.substring(0, 160),
    };
  }

  return {
    title: "Post - c0deviews",
    description: "Generated by create next app",
  };
}

async function getPost(slug: string) {
  const res = await getPostSlug({ slug });
  return res && res.success ? res.data : null;
}

export default async function SlugPage({
  params,
}: {
  params: { slug: string };
}) {
  const post = await getPost(params.slug);
  return <PostComponent initialPost={post} />;
}
