import { Metadata } from "next";
import ProfileComponent from "@/components/profile";
import { getUserByUsername } from "@/app/(auth)/user.api";

export async function generateMetadata({
  params,
}: {
  params: { username: string };
}): Promise<Metadata> {
  const res = await getUserByUsername({ username: params.username });

  if (res && res.success) {
    return {
      title: `${res.user.data.username} - c0deviews`,
      description: "desc",
    };
  }

  return {
    title: "Post | c0deviews",
    description: "Generated by create next app",
  };
}

async function getUser(username: string) {
  const res = await getUserByUsername({ username });
  return res && res.success ? res.user : null;
}

export default async function ProfilePage({
  params,
}: {
  params: { username: string };
}) {
  const user = await getUser(params.username);
  return <ProfileComponent initialUser={user} />;
}
